#ifndef MapBehavior
#define MapBehavior
#include <motionAuxiliarFunctions.hpp>
#include <ledAuxiliarFunctions.hpp>
#include <Kick.hpp>
//#include <turnToBall.hpp>
//#include <walkToBall.hpp>
//#include <Align.hpp>
#include <deadStiffness.hpp>
#include <GmCtrlInitial.hpp>
#include <GmCtrlFinished.hpp>
#include <refPickup.hpp>
#include <GmCtrlReady.hpp>
#include <LookForBall.hpp>
#include <ReadyMachine.hpp>
#include <getUpBack.hpp>
//#include <seekBall.hpp>
#include <sonarRight.hpp>
#include <turnLeft.hpp>
#include <GmCtrlPlaying.hpp>
#include <GmCtrlSet.hpp>
#include <behavior.hpp>
#include <walk.hpp>
#include <Start.hpp>
#include <turnRight.hpp>
#include <sonarLeft.hpp>
#include <sonarMiddle.hpp>
#include <getUpFront.hpp>
//#include <newWalk.hpp>
#include <GmCtrlPenalized.hpp>
#include <Sonar.hpp>
#include <BehaviorBase.hpp>
#include <stayStill.hpp>
#include <vira90.hpp>
#endif
