# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(VISION_INCLUDE_DIRS "/home/yuri/nao/workspace/UnBeatables/UnBeatables/robocupCode/vision;/home/yuri/nao/workspace/UnBeatables/UnBeatables/robocupCode/vision/include;/home/yuri/nao/workspace/UnBeatables/UnBeatables/robocupCode/motion_integracao/runswift;/home/yuri/nao/workspace/UnBeatables/UnBeatables/robocupCode/common;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/libnaoqi/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/boost/include/boost-1_55;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/libnaoqi/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/openni2/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/udev/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/usb_1/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/tiff/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/jpeg/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/ffmpeg/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/bzip2/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/v4l/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/png/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/gstreamer/include/gstreamer-0.10;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/glib2/include/glib-2.0;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/glib2/lib/glib-2.0/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/cross/i686-aldebaran-linux-gnu/sysroot/usr/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/ffi/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/xml2/include/libxml2;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/zlib/include;/home/yuri/nao/devtools/ctc-linux64-atom-2.1.3.3/tbb/include" CACHE INTERNAL "" FORCE)
 
set(VISION_LIBRARIES "general;/home/yuri/nao/workspace/UnBeatables/UnBeatables/robocupCode/vision/build-atom/sdk/lib/naoqi/libvision.so" CACHE INTERNAL "" FORCE)
 
set(VISION_TARGET "vision" CACHE INTERNAL "" FORCE)

set(VISION_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(VISION_DEPENDS "ALVISION;ALEXTRACTOR;ALTHREAD;ALPROXIES;ALCOMMON;BOOST_SIGNALS;RTTOOLS;ALVALUE;ALERROR;QIMESSAGING;QITYPE;QI;BOOST_CHRONO;BOOST_FILESYSTEM;BOOST_PROGRAM_OPTIONS;BOOST_REGEX;BOOST;BOOST_DATE_TIME;BOOST_SYSTEM;BOOST_LOCALE;BOOST_THREAD;OPENCV2_HIGHGUI;OPENCV2_IMGPROC;OPENNI2;UDEV;USB_1;TIFF;JPEG;FFMPEG;BZIP2;V4L;PNG;GSTREAMER;GMODULE;DL;GOBJECT;GTHREAD;GLIB2;PTHREAD;RT;FFI;XML2;OPENCV2_OBJDETECT;OPENCV2_FEATURES2D;OPENCV2_FLANN;OPENCV2_CORE;ZLIB;TBB" CACHE INTERNAL "" FORCE)
 