pipeline {
    agent any

    stages {
        stage('Build and Test') {
            steps {
                sh './gradlew build'
            }
        }
        stage('Document'){
            steps {
                sh './gradlew groovydoc'
            }
        }
        stage('Launch Sonar'){
            steps {
                sh './gradlew sonarqube'
            }
        }
    }
}