#to use: make prog='program_name'
INC= -I '/home/gabriel/includes'
SRC=
FLAGS = -D  REMOTE

all:
	clear
	g++ -o  ${prog} ${prog}'.cpp' $(INC) -g $(FLAGS) -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video

	
